"""empty message

Revision ID: 0d220e386cdc
Revises: 286a1e9dd221
Create Date: 2019-04-30 11:59:08.281746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d220e386cdc'
down_revision = '286a1e9dd221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'data')
    # ### end Alembic commands ###
