"""empty message

Revision ID: 286a1e9dd221
Revises: c648f056724a
Create Date: 2019-04-30 11:50:52.528224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286a1e9dd221'
down_revision = 'c648f056724a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('operation_code', sa.String(length=120), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=120), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history')
    op.drop_table('operation')
    # ### end Alembic commands ###
