"""empty message

Revision ID: 3ad7c2b054b0
Revises: 0d220e386cdc
Create Date: 2019-04-30 17:56:35.325780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad7c2b054b0'
down_revision = '0d220e386cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'active')
    # ### end Alembic commands ###
