"""empty message

Revision ID: c648f056724a
Revises: a3fe567b740f
Create Date: 2019-04-29 15:18:05.306188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c648f056724a'
down_revision = 'a3fe567b740f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hex', sa.String(length=128), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_hex'), 'token', ['hex'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_hex'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
